### PR TITLE
Initial support for tracking submissions with Segment

### PR DESCRIPTION
**Pull request by DavisRayM**
Based on #1871 

## Changes / Features implemented

- analytics module to track events

### CODE REVIEW

**Comment by pld** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/onaio/onadata/pullRequest?prid=6002799&bid=19679525)

**Comment by pld** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/onaio/onadata/pullRequest?prid=6002799&bid=19679525)

**Comment by pld** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/onaio/onadata/pullRequest?prid=6002799&bid=19679525)

**Review by ukanga — APPROVED** [review]

**Review by ivermac — APPROVED** [review]
Hey @DavisRayM, I just wanted to mention that I really like the way you have made use of the class decorators which is very clean and easy to use. Good job on this 👍 !

**Pull request merged**
