### PR TITLE
Grant new users formbuilder perms

### LINKED ISSUE #892: Grant formbuilder object permissions on creation of a user profile
New users are the getting the following error when clicking the formbuilder link on zebra because they do not have object permissions. These permissions should be granted when new accounts/profiles are created.

### PR DESCRIPTION
**Pull request by ivermac**
closes #892

### CODE REVIEW

**Comment by ivermac** [comment]
I can't seem to find a better way to test a `post_save` signal - there aren't any (or I haven't seen) any signal tests on the repo. Using `@patch` decorator on [this test case](https://github.com/onaio/onadata/blob/master/onadata/apps/main/tests/test_user_profile.py#L42) and checking if the mock was called i.e `self.assertTrue(mock.called)` failed for me - returned false. If anyone has a better way to handle this, please mention it here.

**Comment by skambo** [comment]
@ivermac on stage, after creating a new acc, the error is still there

screen shot 2017-01-30 at 12 31 10 pm

**Comment by skambo** [comment]
@ivermac @denniswambua It works now for new users

**Comment by ivermac** [comment]
See the second comment on the PR

**Comment by ivermac** [comment]
I think what should be tested is whether the signal function was called or not.

**Comment by pld** [comment]
@ivermac​ sounds good, please add tests for what Dennis and you identified
as testable

**Pull request merged**
