### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by parthibd**
### Changes / Features implemented

Update Dockerfile

### Steps taken to verify this change does what is intended

Manually tested with `docker`

### Side effects of implementing this change

None

Closes #

[1958](https://github.com/onaio/onadata/issues/1958)

### CODE REVIEW

**Comment by DavisRayM** [comment]
Thanks for the PR @parthibd, Looks good. I think we should remove the version lock on the `apt-get install` command much like this [Dockerfile](https://github.com/onaio/onadata/blob/1f048b809eb794e81ef13830b4b4776a0eb021d3/docker/onadata-uwsgi/Dockerfile#L37-L66) in order to avoid this error popping up again whenever the apt version is removed.

**Comment by parthibd** [comment]
@DavisRayM Thank you for your response . Should I go ahead and test it out by removing the version locks ? I will make another PR.

**Comment by DavisRayM** [comment]
> @DavisRayM Thank you for your response . Should I go ahead and test it out by removing the version locks ? I will make another PR.

Yes, please go ahead and test it out. _I'd recommend you create a PR from a sub-branch too, something like `1959-update-dockerfile` instead of `master`._

**Comment by parthibd** [comment]
> 
> 
> > @DavisRayM Thank you for your response . Should I go ahead and test it out by removing the version locks ? I will make another PR.
> 
> Yes, please go ahead and test it out. _I'd recommend you create a PR from a sub-branch too, something like `1959-update-dockerfile` instead of `master`._
> 
> Helpful [link](https://github.com/onaio/onadata/blob/master/CONTRIBUTING.MD#3-code-contributions--pull-requests-) for Signed commits and a few guidelines

Thank you for the info . I'll keep that in mind.

**Pull request closed without merging**
