### PR TITLE
Add throttling based on URL

### PR DESCRIPTION
**Pull request by FrankApiyo**
### Side effects of implementing this change

**Before submitting this PR for review, please make sure you have:**

  - [x] Included tests
  - [ ] Updated documentation

Closes #

### CODE REVIEW

**Review by kelvin-muchiri — APPROVED** [review]

**Review by ukanga — COMMENTED** [review]
This targets only submissions. Can it be generic enough to handle different paths and request methods?

**Comment by FrankApiyo** [comment]
> This targets only submissions. Can it be generic enough to handle different paths and request methods?

It seemed appropriate to only target the submission endpoint(s) for now because performance/scaling issues triggered on the submission endpoints.

**Review by ukanga — COMMENTED** [review]
Can we throttle more than one endpoint at a time?

**Comment by FrankApiyo** [comment]
These changes have been superseded by https://github.com/onaio/onadata/pull/2685

**Pull request closed without merging**
