### PR TITLE
Rename variable 'gen_consistent' to 'consistent_urls'

### PR DESCRIPTION
**Pull request by DavisRayM**
### Changes / Features implemented

- Rename variable `gen_consistent` to `consistent_urls`

### Steps taken to verify this change does what is intended

CI Tests

### Side effects of implementing this change

None

### CODE REVIEW

**Comment by DavisRayM** [comment]
> The change looks good. Why is the value of `consistent_urls` a boolean?

It's used as a "flag" of sorts to determine whether we should generate the enketo urls consistently [here](https://github.com/onaio/onadata/pull/1799/files#diff-0c09bacc2f47a378a518ee619d348093R319).

**Comment by DavisRayM** [comment]
> > The change looks good. Why is the value of `consistent_urls` a boolean?
> 
> It's used as a "flag" of sorts to determine whether we should generate the enketo urls consistently [here](https://github.com/onaio/onadata/pull/1799/files#diff-0c09bacc2f47a378a518ee619d348093R319).

I'm actually not entirely sure if we'll ever have to recreate the old urls ? Might just be better to fully phase out the old way of generating enketo urls ?

**Comment by ivermac** [comment]
Can I suggest we rename `consistent_urls` to `generate_ consistent_urls`?

**Comment by DavisRayM** [comment]
> Can I suggest we rename `consistent_urls` to `generate_consistent_urls` 🙈?

Sure, your suggestion seems more verbose I believe. I'll make this change.

**Pull request merged**
