### PR TITLE
Fix issue where file uploads were automatically soft deleted

### LINKED ISSUE #1815: Files sent alongside a submission are automatically soft_deleted
### Environmental Information

- Onadata version: v2.3.1

### Problem description

Whenever a new submission with an attachment is made the attachments are automatically soft deleted.

### Expected behavior

Submission attachments should not be soft-deleted on creation.

### Steps to reproduce the behavior

1. Create a form with a `file` field.
2. Make a submission to the form
3. Check the data returned on `api/v1/data/<instance_id>`. _The \_attachements list will be empty_
4. (Optional) Within the python shell check the instances attachments `instance.attachments.all()`. _You'll notice the new attachment has been soft deleted: Has `deleted_at` set._

### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

### PR DESCRIPTION
**Pull request by DavisRayM**
### Changes / Features implemented

- Add `file` to `KNOWN_MEDIA_TYPES`
- Update `test_replaced_attachments_not_tracked` test

### Pending Work

- Add test for `recover_deleted_attachments` management function

### Steps taken to verify this change does what is intended

- Updated tests
- [x] QA

### Side effects of implementing this change

Closes #1815

### CODE REVIEW

**Comment by DavisRayM** [comment]
Noticed duplicate attachments for new submissions while testing this out, investigating further to see if it's a bug.

**Comment by DavisRayM** [comment]
> Noticed duplicate attachments for new submissions while testing this out, investigating further to see if it's a bug.

Not entirely sure what caused this... Unable to replicate it at the moment though.

**Comment by faith-mutua** [comment]
@DavisRayM The attachment list now has the uploaded file. I wonder why we still have the `media not uploaded successfully` tooltip as shown in the screenshot below. 

Screen Shot 2020-04-29 at 13 45 26

**Comment by DavisRayM** [comment]
That's weird... not entirely sure if that's a bug on the api or the frontend... If the information is returned on the endpoint I think this is an issue on the frontend. I'll try to replicate this.
> @DavisRayM The attachment list now has the uploaded file. I wonder why we still have the `media not uploaded successfully` tooltip as shown in the screenshot below.
> 
> Screen Shot 2020-04-29 at 13 45 26

**Comment by faith-mutua** [comment]
@DavisRayM document files are now included under `-attachments`. The files now have downloadable links on the table tab. This has passed QA.

**Pull request merged**
